from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import trade_loop_telegram_notify as tn  # noqa: E402

STATUS_WITH_QUEUE = """# Trading loop status — 2026-09-12

## 4. Paper systems

| line | status |

## 5. Decisions only a human can take

- record closure of nq_orb_paper (REJECTED by its own gates)
- consider ROLLBACK of applied rule `review_pause_D2`: post-apply mean R 0.1 vs baseline 0.4

Generated by tools/trade_loop_digest.py.
"""

STATUS_EMPTY_QUEUE = """# Trading loop status — 2026-09-12

## 5. Decisions only a human can take

- none today — the loop is accumulating forward evidence
"""

LEDGER = {"hypotheses": {
    "a": {"status": "APPLIED"}, "b": {"status": "APPLIED"},
    "c": {"status": "SHADOW"}}}
SCORECARD = [{"line": "x", "status": "REJECTED"}, {"line": "y", "status": "SHADOW"}]


def test_extract_queue_reads_only_section_five():
    q = tn.extract_queue(STATUS_WITH_QUEUE)
    assert len(q) == 2
    assert q[0].startswith("record closure of nq_orb_paper")
    assert "ROLLBACK" in q[1]


def test_message_lists_decisions_and_health():
    msg = tn.build_message(STATUS_WITH_QUEUE, LEDGER, SCORECARD, now=datetime(2026, 9, 12, 1, 35))
    assert "Your decisions (2):" in msg
    assert "record closure of nq_orb_paper" in msg
    assert "2 applied" in msg and "1 shadow" in msg
    assert "1 rejected" in msg
    assert "Observation only" in msg
    assert len(msg) <= tn.MAX_CHARS


def test_message_when_nothing_to_do_still_reports():
    msg = tn.build_message(STATUS_EMPTY_QUEUE, LEDGER, SCORECARD, now=datetime(2026, 9, 12, 1, 35))
    assert "No decisions for you today" in msg
    assert "hypotheses" in msg  # heartbeat: proves the loop ran


def test_missing_status_page_is_flagged_not_silent():
    msg = tn.build_message("", None, None, now=datetime(2026, 9, 12, 1, 35))
    assert "missing" in msg.lower()
    assert "scheduled tasks" in msg


def test_long_queue_is_truncated_with_pointer():
    many = "## 5. Decisions only a human can take\n\n" + "\n".join(
        f"- decision number {i}" for i in range(12))
    msg = tn.build_message(many, LEDGER, SCORECARD, now=datetime(2026, 9, 12, 1, 35))
    assert f"(+{12 - tn.MAX_QUEUE_ITEMS} more on the page)" in msg
    assert len(msg) <= tn.MAX_CHARS


def test_dry_run_sends_nothing(monkeypatch, capsys):
    called = []
    monkeypatch.setattr(tn, "send_telegram_message", lambda *a, **k: called.append(a) or True)
    rc = tn.main(["--dry-run"])
    assert rc == 0
    assert called == []
    assert "SPARTA trading loop" in capsys.readouterr().out
